In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df = pd.read_excel("IMPORTACION-VOLUMEN-2024-05.xlsx")

# Eliminar filas completamente vacías
df_cleaned = df.dropna(how='all')

# Eliminar columnas completamente vacías
df_cleaned = df_cleaned.dropna(axis=1, how='all')

# Usar la fila 5 como encabezado
df_cleaned.columns = df_cleaned.iloc[1]

# Eliminar filas anteriores a la fila de encabezado
df_cleaned = df_cleaned[2:]

# Resetear el índice
df_cleaned.reset_index(drop=True, inplace=True)

file_name = "depurado.csv"
# Guardar el DataFrame depurado en un archivo CSV
df_cleaned.to_csv(file_name, index=False)

print(f"Archivo depurado guardado como {file_name}")

Archivo depurado guardado como depurado.csv

In [9]:
data = pd.read_csv("depurado.csv")
data

,Fecha,Aceites lubricantes,Asfalto,Bunker,Ceras,Combustible turbo jet,Diesel bajo azufre,Diesel ultra bajo azufre,Gas licuado de petróleo,Gasolina de aviación,...,Naftas,Petcoke,Petróleo crudo,Solventes,Butano,Diesel alto azufre,MTBE,Orimulsión,Petróleo reconstituido,Total importación
0,2001-01-01 00:00:00,0.00,27748.99,214581.84,0.00,0.00,0.00,0.00,194065.738095,820.00,...,0.00,0.00,0.0,0.00,0.0,566101.99,8402.0,0.0,715344.0,2.312639e+06
1,2001-02-01 00:00:00,0.00,7503.57,294609.00,0.00,0.00,0.00,0.00,170703.380952,3054.00,...,0.00,0.00,0.0,0.00,0.0,489525.80,0.0,0.0,370166.0,1.769209e+06
2,2001-03-01 00:00:00,0.00,26304.32,315263.80,0.00,0.00,0.00,0.00,161837.371429,677.00,...,0.00,0.00,0.0,0.00,0.0,575559.68,0.0,0.0,360530.0,1.945770e+06
3,2001-04-01 00:00:00,0.00,7885.89,205653.00,0.00,0.00,0.00,0.00,163048.642857,3399.00,...,0.00,0.00,0.0,0.00,0.0,437745.42,8184.0,0.0,359527.0,1.623638e+06
4,2001-05-01 00:00:00,0.00,8443.16,278371.30,0.00,0.00,0.00,0.00,171518.861905,585.00,...,0.00,0.00,0.0,0.00,0.0,552609.13,12680.0,0.0,723346.0,2.262727e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,2024-03-01 00:00:00,27993.04,5633.41,163119.06,0.00,105710.45,1477038.00,5007.48,675157.480000,0.00,...,263.28,523701.86,2869.0,3782.28,0.0,0.00,0.0,0.0,0.0,4.451150e+06
279,2024-04-01 00:00:00,37444.60,7990.99,77253.65,33.52,85752.17,1294706.12,0.00,473940.660000,3351.23,...,40.00,0.00,7802.0,23555.38,0.0,0.00,0.0,0.0,0.0,3.589097e+06
280,2024-05-01 00:00:00,31035.55,10483.78,544682.15,91.83,94606.00,1470870.09,0.00,684864.460000,0.00,...,242.22,518800.00,3845.0,14929.21,0.0,0.00,0.0,0.0,0.0,5.013967e+06
281,Fuente: informes mensuales de titulares de lic...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,Nota: Información sujeta a actualización por p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# Obtén los encabezados
headers = list(data.columns)

headers

['Fecha',
 'Aceites lubricantes',
 'Asfalto ',
 'Bunker',
 'Ceras',
 'Combustible turbo jet',
 'Diesel bajo azufre',
 'Diesel ultra bajo azufre',
 'Gas licuado de petróleo',
 'Gasolina de aviación',
 'Gasolina regular',
 'Gasolina superior',
 'Grasas lubricantes',
 'Kerosina',
 'Mezclas oleosas',
 'Naftas',
 'Petcoke',
 'Petróleo crudo',
 'Solventes',
 'Butano',
 'Diesel alto azufre',
 'MTBE',
 'Orimulsión',
 'Petróleo reconstituido',
 'Total importación']

In [11]:
data_cleaned = data.dropna()
data_cleaned

,Fecha,Aceites lubricantes,Asfalto,Bunker,Ceras,Combustible turbo jet,Diesel bajo azufre,Diesel ultra bajo azufre,Gas licuado de petróleo,Gasolina de aviación,...,Naftas,Petcoke,Petróleo crudo,Solventes,Butano,Diesel alto azufre,MTBE,Orimulsión,Petróleo reconstituido,Total importación
0,2001-01-01 00:00:00,0.00,27748.99,214581.84,0.00,0.00,0.00,0.00,194065.738095,820.00,...,0.00,0.00,0.0,0.00,0.0,566101.99,8402.0,0.0,715344.0,2.312639e+06
1,2001-02-01 00:00:00,0.00,7503.57,294609.00,0.00,0.00,0.00,0.00,170703.380952,3054.00,...,0.00,0.00,0.0,0.00,0.0,489525.80,0.0,0.0,370166.0,1.769209e+06
2,2001-03-01 00:00:00,0.00,26304.32,315263.80,0.00,0.00,0.00,0.00,161837.371429,677.00,...,0.00,0.00,0.0,0.00,0.0,575559.68,0.0,0.0,360530.0,1.945770e+06
3,2001-04-01 00:00:00,0.00,7885.89,205653.00,0.00,0.00,0.00,0.00,163048.642857,3399.00,...,0.00,0.00,0.0,0.00,0.0,437745.42,8184.0,0.0,359527.0,1.623638e+06
4,2001-05-01 00:00:00,0.00,8443.16,278371.30,0.00,0.00,0.00,0.00,171518.861905,585.00,...,0.00,0.00,0.0,0.00,0.0,552609.13,12680.0,0.0,723346.0,2.262727e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276,2024-01-01 00:00:00,26693.78,7837.29,99680.22,105.62,101415.50,1409097.15,6710.98,701570.800000,0.00,...,123.60,264918.62,0.0,15383.87,0.0,0.00,0.0,0.0,0.0,4.263216e+06
277,2024-02-01 00:00:00,21374.61,5313.11,143951.95,95.09,87352.10,1236861.75,4639.33,916541.700000,5978.37,...,80.00,534021.57,2057.0,24524.03,0.0,0.00,0.0,0.0,0.0,4.377134e+06
278,2024-03-01 00:00:00,27993.04,5633.41,163119.06,0.00,105710.45,1477038.00,5007.48,675157.480000,0.00,...,263.28,523701.86,2869.0,3782.28,0.0,0.00,0.0,0.0,0.0,4.451150e+06
279,2024-04-01 00:00:00,37444.60,7990.99,77253.65,33.52,85752.17,1294706.12,0.00,473940.660000,3351.23,...,40.00,0.00,7802.0,23555.38,0.0,0.00,0.0,0.0,0.0,3.589097e+06
280,2024-05-01 00:00:00,31035.55,10483.78,544682.15,91.83,94606.00,1470870.09,0.00,684864.460000,0.00,...,242.22,518800.00,3845.0,14929.21,0.0,0.00,0.0,0.0,0.0,5.013967e+06